### ISSUE TITLE
Similarity score

### ISSUE THREAD

**Issue by mavencode01** [jrfaller/gumtree#7]
I found your project and looks interesting but am wondering if it's possible to use it to get the similarity score between two source files ?

**Comment by npalix** [comment]
You can check the various output formats available, like the XML one or the annotated XML.
https://github.com/jrfaller/gumtree/tree/master/client/src/main/java/fr/labri/gumtree/client/ui/xml

According to the definition of sentences (line, statement..) you want to compute the similarity score
I guess the annotated XML output will help you. Check the "--output asrc" option.
